function private:builddate{
   $date = Get-Date -UFormat "%A, %B %e, %Y %t %r"
   $csclass = 'public static class BuildDate { readonly static public string sBuildDate = "'
   $csclass = $csclass + $date
   $csclass = $csclass + '"; } 
   // This file is generated by the building script. '
   #Write-Output $csclass > "KthuraLauncher/builddate.cs"
   Write-Output $csclass | out-file -encoding ASCII "builddate.cs"
   write-host "Build date: " -nonewline -foregroundcolor yellow
   write-host $date -foregroundcolor cyan
   
}

builddate